# Dependabot version updates.
# Documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(dev-deps)"
    ignore:
      # Do not update @angular dependencies at all; these are updated manually
      - dependency-name: "@angular*"
      # Do not update major versions
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
