# Dockerfile.web
# This Dockerfile leverages multi-stage builds so
# only necessary build artifacts and resources are
# included in the final image.

# Enable passing the tag of the Node.js image as a build argument,
# and define a default tag in case the build argument is not passed.
# The Node.js image is used as the build image of the app,
# https://hub.docker.com/_/node/.
ARG NODE_IMAGE_TAG=22-alpine

# Enable passing the tag of the nginx image as a build argument,
# and define a default tag in case the build argument is not passed.
# The nginx image is used as the final image of the app,
# https://hub.docker.com/_/nginx.
ARG NGINX_IMAGE_TAG=1.28.0-alpine

# 1) Build Angular app
FROM node:${NODE_IMAGE_TAG} AS build
WORKDIR /app

# Install deps with caching
COPY package.json package-lock.json ./
RUN npm ci

# Copy sources and build
COPY . .
RUN npm run build

# 2) Serve with nginx
FROM nginx:${NGINX_IMAGE_TAG} AS final
# Copy nginx conf file
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
# Copy the dist/browser folder from the build image to the final, runtime image.
COPY --from=build /app/dist/browser /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
