/**
 * This prebuild script is used to extract the `version` of the app
 * from `package.json` and write it to a ts-file, which the app
 * can import for displaying the app version in the page footer.
 */

const { writeFileSync } = require('fs');
const { version } = require('./package.json');

const versionFilePath = './src/assets/config/app-version.ts';
const content = `
// This file is automatically generated by the build script.
export const APP_VERSION = '${version}';
`;

writeFileSync(versionFilePath, content, { encoding: 'utf8' });
console.log(`App version file generated: ${version}`);
