name: "Build and push Docker image"

# Run this workflow when a new commit in the "main" branch
# or release/tag is pushed.
on:
  push:
    branches:
      - main
    tags:
      - '*'

  # Allow this workflow to be manually triggered from the actions
  # tab (for debugging).
  workflow_dispatch:

# Allow job to read repository and write image/package to ghcr.io.
permissions:
    contents: read
    packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # Define tag of official Node.js image to be used as the base image
      # for the build, this is passed as a build argument to Dockerfile
      # https://hub.docker.com/_/node/.
      NODE_IMAGE_TAG: 22-alpine
      # Define tag of official nginx image to be used as the final image
      # for the build, this is passed as a build argument to Dockerfile
      # https://hub.docker.com/_/nginx
      NGINX_IMAGE_TAG: 1.28.2-alpine

    steps:
      # 1) Check out repository.
      - name: Check out repository
        uses: actions/checkout@v6

      # 2) Authenticate to GitHub Container Registry.
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3) Create a Buildx builder. Buildx uses BuildKit under the hood.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4) Pull metadata from GitHub events (so we can use release version
      # number).
      - name: Pull metadata from GitHub
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # 5) Build image, tagging with the release tag and "latest" on a
      # release, or with "main" if built against main (commit push) or
      # built using workflow_dispatch.
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          pull: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_IMAGE_TAG=${{ env.NODE_IMAGE_TAG }}
            NGINX_IMAGE_TAG=${{ env.NGINX_IMAGE_TAG }}
